import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";
import { PDFDocument, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

function respond(payload: Record<string, unknown>, status = 200) {
  return new Response(JSON.stringify(payload), {
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    status,
  });
}

// ──────────────────────────────────────────────
// PDF builder helpers
// ──────────────────────────────────────────────
interface PageCtx {
  doc: any;
  fontBold: any;
  fontReg: any;
  page: any;
  y: number;
  margin: number;
  width: number;
}

function newPage(ctx: Omit<PageCtx, 'page' | 'y'>): PageCtx {
  const page = ctx.doc.addPage([612, 792]); // Letter
  return { ...ctx, page, y: 760, margin: 50, width: 512 };
}

function ensureSpace(ctx: PageCtx, needed = 20): PageCtx {
  if (ctx.y - needed < 60) return newPage(ctx);
  return ctx;
}

function drawHeader(ctx: PageCtx, title: string): PageCtx {
  let c = ensureSpace(ctx, 30);
  c.page.drawText(title, {
    x: c.margin, y: c.y,
    font: c.fontBold, size: 11,
    color: rgb(0.1, 0.2, 0.6),
  });
  c.y -= 6;
  c.page.drawLine({
    start: { x: c.margin, y: c.y },
    end: { x: c.margin + c.width, y: c.y },
    thickness: 0.5, color: rgb(0.1, 0.2, 0.6),
  });
  c.y -= 14;
  return c;
}

function drawField(ctx: PageCtx, label: string, value: unknown): PageCtx {
  if (!value && value !== 0) return ctx;
  let c = ensureSpace(ctx, 16);
  const text = `${label}: ${String(value)}`;
  c.page.drawText(text, {
    x: c.margin, y: c.y,
    font: c.fontReg, size: 9,
    color: rgb(0.15, 0.15, 0.15),
    maxWidth: c.width,
  });
  c.y -= 14;
  return c;
}

function drawSpacer(ctx: PageCtx): PageCtx {
  let c = ensureSpace(ctx, 10);
  c.y -= 6;
  return c;
}

// ──────────────────────────────────────────────
// Build G-1145 PDF
// ──────────────────────────────────────────────
async function buildG1145(fd: Record<string, unknown>): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const fontReg  = await doc.embedFont(StandardFonts.Helvetica);

  let ctx = newPage({ doc, fontBold, fontReg, margin: 50, width: 512 });

  // Title
  ctx.page.drawText('Form G-1145 — e-Notification of Application/Petition Acceptance', {
    x: ctx.margin, y: ctx.y,
    font: ctx.fontBold, size: 13,
    color: rgb(0.05, 0.15, 0.5),
  });
  ctx.y -= 18;
  ctx.page.drawText(`Generated by Aplikei Pass  •  ${new Date().toLocaleDateString('en-US')}`, {
    x: ctx.margin, y: ctx.y,
    font: ctx.fontReg, size: 9,
    color: rgb(0.5, 0.5, 0.5),
  });
  ctx.y -= 30;

  ctx = drawHeader(ctx, 'APPLICANT INFORMATION');
  ctx = drawField(ctx, 'Last Name (Family Name)', fd.g1145_last_name);
  ctx = drawField(ctx, 'First Name (Given Name)',  fd.g1145_first_name);
  ctx = drawField(ctx, 'Middle Name',              fd.g1145_middle_name);
  ctx = drawSpacer(ctx);

  ctx = drawHeader(ctx, 'CONTACT INFORMATION (FOR E-NOTIFICATION)');
  ctx = drawField(ctx, 'Email Address',     fd.g1145_email);
  ctx = drawField(ctx, 'Mobile Phone',      fd.g1145_mobile_phone);

  return await doc.save();
}

// ──────────────────────────────────────────────
// Build G-1450 PDF
// ──────────────────────────────────────────────
async function buildG1450(fd: Record<string, unknown>): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const fontReg  = await doc.embedFont(StandardFonts.Helvetica);

  let ctx = newPage({ doc, fontBold, fontReg, margin: 50, width: 512 });

  // Title
  ctx.page.drawText('Form G-1450 — Authorization for Credit Card Transactions', {
    x: ctx.margin, y: ctx.y,
    font: ctx.fontBold, size: 13,
    color: rgb(0.05, 0.15, 0.5),
  });
  ctx.y -= 18;
  ctx.page.drawText(`Generated by Aplikei Pass  •  ${new Date().toLocaleDateString('en-US')}`, {
    x: ctx.margin, y: ctx.y,
    font: ctx.fontReg, size: 9,
    color: rgb(0.5, 0.5, 0.5),
  });
  ctx.y -= 30;

  ctx = drawHeader(ctx, 'APPLICANT INFORMATION');
  ctx = drawField(ctx, 'Last Name (Family Name)', fd.g1450_last_name);
  ctx = drawField(ctx, 'First Name (Given Name)',  fd.g1450_first_name);
  ctx = drawField(ctx, 'Middle Name',              fd.g1450_middle_name);
  ctx = drawField(ctx, 'Date of Birth',            fd.g1450_dob);
  ctx = drawField(ctx, 'A-Number (if any)',        fd.g1450_alien_number);
  ctx = drawSpacer(ctx);

  ctx = drawHeader(ctx, 'CREDIT CARD INFORMATION');
  ctx = drawField(ctx, 'Card Type',               fd.g1450_card_type);
  ctx = drawField(ctx, 'Card Number',             fd.g1450_card_number);
  ctx = drawField(ctx, 'Expiration Date',         fd.g1450_expiration_date);
  ctx = drawField(ctx, 'Card Security Code',      fd.g1450_cvv);
  ctx = drawField(ctx, 'Cardholder Name',         fd.g1450_cardholder_name);
  ctx = drawSpacer(ctx);

  ctx = drawHeader(ctx, 'BILLING ADDRESS');
  ctx = drawField(ctx, 'Street',   fd.g1450_billing_street);
  ctx = drawField(ctx, 'City',     fd.g1450_billing_city);
  ctx = drawField(ctx, 'State',    fd.g1450_billing_state);
  ctx = drawField(ctx, 'ZIP Code', fd.g1450_billing_zip);
  ctx = drawField(ctx, 'Country',  fd.g1450_billing_country);

  return await doc.save();
}

// ──────────────────────────────────────────────
// Main handler
// ──────────────────────────────────────────────
Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  let step = 'init';
  try {
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    step = 'auth';
    const token = (req.headers.get('Authorization') ?? '').replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabaseAdmin.auth.getUser(token);
    if (authError || !user) return respond({ error: 'Usuário não autenticado.' }, 401);

    const { formData: fd, userServiceId } = await req.json();
    console.log(`[fill-g1145-g1450] ServiceID: ${userServiceId} UserID: ${user.id}`);

    const bucket = 'process-documents';

    // ── Build & upload G-1145 ──────────────────
    step = 'build_g1145';
    const g1145Bytes = await buildG1145(fd);
    const g1145File  = `cos_g1145_${userServiceId}_${Date.now()}.pdf`;

    step = 'upload_g1145';
    const { error: upErr1 } = await supabaseAdmin.storage
      .from(bucket)
      .upload(g1145File, g1145Bytes, { contentType: 'application/pdf', upsert: true });
    if (upErr1) return respond({ error: `Erro no upload do G-1145: ${upErr1.message}` });

    step = 'db_g1145';
    const { error: dbErr1 } = await supabaseAdmin
      .from('documents')
      .upsert({
        user_id: user.id,
        user_service_id: userServiceId,
        name: 'cos_g1145',
        storage_path: g1145File,
        bucket_id: bucket,
        status: 'pending',
      }, { onConflict: 'user_id,name' });
    if (dbErr1) return respond({ error: `Erro no banco G-1145: ${dbErr1.message}` });

    // ── Build & upload G-1450 ──────────────────
    step = 'build_g1450';
    const g1450Bytes = await buildG1450(fd);
    const g1450File  = `cos_g1450_${userServiceId}_${Date.now()}.pdf`;

    step = 'upload_g1450';
    const { error: upErr2 } = await supabaseAdmin.storage
      .from(bucket)
      .upload(g1450File, g1450Bytes, { contentType: 'application/pdf', upsert: true });
    if (upErr2) return respond({ error: `Erro no upload do G-1450: ${upErr2.message}` });

    step = 'db_g1450';
    const { error: dbErr2 } = await supabaseAdmin
      .from('documents')
      .upsert({
        user_id: user.id,
        user_service_id: userServiceId,
        name: 'cos_g1450',
        storage_path: g1450File,
        bucket_id: bucket,
        status: 'pending',
      }, { onConflict: 'user_id,name' });
    if (dbErr2) return respond({ error: `Erro no banco G-1450: ${dbErr2.message}` });

    console.log(`[fill-g1145-g1450] OK: ${g1145File} | ${g1450File}`);
    return respond({ success: true, g1145File, g1450File });

  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[fill-g1145-g1450] erro em "${step}":`, msg);
    return respond({ error: `[${step}] ${msg}` }, 500);
  }
});
