const landing = {
  nav: { pain: "Problem", automation: "Solution", howItWorks: "How it works", pricing: "Plans", signIn: "Sign in", bookDemo: "Book a demo" },
  hero: {
    badge: "Digital operations for immigration firms",
    title: "Turn your immigration firm into a",
    titleAccent: "digital operation.",
    lead: "Sell immigration services as digital solutions, with personalized checkout, organized processes, an integrated team and AI to support the operation.",
    ctaPrimary: "Get started now", ctaSecondary: "See how it works",
    stat1: { v: "−70%", l: "less time per case" }, stat2: { v: "10k+", l: "active processes" }, stat3: { v: "3×", l: "more cases per team" },
    mockTitle: "Cases", mockSearch: "Search cases…", mockFilter: "Filter",
    mockCols: ["Client", "Status", "Visa", "Progress", "Start"],
    floatLabel: "Digital operation",
    statusLabels: { b: "Status change", g: "Done", "": "In review" },
  },
  logos: { label: "Firms already operating with Aplikei", hint: "Swipe to see more logos" },
  pain: {
    kicker: "Problem", title: "Your firm grew. Did your operation keep up?",
    lead: "Many immigration firms start with WhatsApp, spreadsheets, payment links and documents sent through different channels. It works at first. But as volume grows, the operation breaks: messages get lost, documents are scattered, payments need manual checking, and the team loses clarity about what is pending.",
    items: [
      { title: "Messages get lost", desc: "Support becomes a fragmented flow across channels and nobody knows exactly what has already been answered." },
      { title: "Documents are scattered", desc: "Files arrive from multiple places and the team wastes time looking for what should already be centralized." },
      { title: "Payments need manual checking", desc: "Finance gets stuck in repetitive verification and the firm depends on parallel controls." },
      { title: "The team becomes dependent on the lawyer", desc: "Without a clear system, the lawyer becomes the center of everything and the operation stops scaling." },
    ],
    barText: "The problem is not using WhatsApp or spreadsheets.",
    barSub: "The problem is depending on them to run complex processes.",
    barBadge: "Less improvisation. More control.",
  },
  solutions: {
    kicker: "Solution", title: "From the first click to the closed case, Aplikei keeps every step in the same flow.", lead: "From financial overview to solution management and case tracking, each module keeps the operation aligned and easier to scale.",
    items: [
      { title: "Overview", badge: "Admin panel" as string | null, desc: "See revenue, fees, active cases and available balance in one place." },
      { title: "Financial analysis", badge: "Revenue tracking" as string | null, desc: "Track growth, monthly performance, solution sales and the transaction mix." },
      { title: "Manage solutions", badge: "Solution catalog" as string | null, desc: "Activate visas, mentorship packages and add-ons with pricing and status control." },
      { title: "Track the case", badge: "Case flow" as string | null, desc: "Follow documents, review stages, seller data and the full client journey." },
    ],
  },
  showcase: {
    kicker: "Platform in action",
    title: "A real workspace for teams that need a clear picture of every active case.",
    lead: "Finances, solutions and case tracking in the same operational flow — so your team always knows what is pending, who is responsible, and what comes next.",
    bullets: [
      "Clear metrics for business and team decisions",
      "One place to monitor all active solutions and cases",
      "A more professional experience for clients and staff",
    ],
  },
  automation: {
    kicker: "Aplikei AI", title: "AI to reduce manual work and give your team more speed.", titleAccent: "in practice",
    features: [
      { title: "Information organization", desc: "AI helps your team organize client data, identify missing items and keep the process clearer." },
      { title: "Operational support", desc: "It can help with operational replies, next steps and repetitive follow-ups without replacing the lawyer." },
      { title: "Less rework", desc: "More speed, more clarity and fewer manual tasks so the operation stays consistent." },
    ],
    engineTitle: "AI applied to operations", engineSub: "Operational assistance active", engineLive: "AI active · focused on routine",
    aiPanel: {
      clientName: "Carlos Silva",
      clientVisa: "F-1 Visa",
      clientStatus: "In progress",
      tasks: [
        { done: true, title: "3 pending items found", sub: "Documents organized automatically" },
        { done: true, title: "Follow-up sent in 12s", sub: "Generated by AI without manual input" },
        { done: false, title: "Request updated I-20", sub: "Next step suggested by AI" },
      ],
      saved: "2h saved on this case",
    },
    ctaFill: "Get started now", ctaReview: "See how it works",
  },
  howItWorks: {
    kicker: "How it works", title: "In a few steps, your firm starts operating digitally.",
    lead: "A direct rollout with clear steps and no operational noise.",
    steps: [
      { n: "01", title: "Register your firm", desc: "Set up your operation, brand identity, team and key information." },
      { n: "02", title: "Activate your solutions", desc: "Create services like B1/B2, F1, RFE, COS, consultations and other processes your firm offers." },
      { n: "03", title: "Configure price and checkout", desc: "Define value, description, required documents and generate a personalized payment link." },
      { n: "04", title: "Manage with AI support", desc: "Track payments, documents, steps, owners and payouts while AI helps your team stay organized." },
    ],
  },
  excellence: {
    kicker: "Client experience", title: "Clients should not feel lost after hiring your firm.",
    cards: [
      { title: "More clarity", desc: "Each client enters a clearer, organized flow without depending on scattered messages." },
      { title: "More professionalism", desc: "Your team knows what to follow and the experience improves from start to finish." },
    ],
    mediaLabel: "[ office / team using Aplikei ]",
  },
  testimonials: {
    kicker: "Before and after", title: "From improvised operation to digital process",
    items: [
      { quote: ["Before, the team lived on WhatsApp and spreadsheets. ", "Now everything is centralized", " in an operation we can actually control."], name: "Ricardo Mendes", role: "Partner · Mendes Lex", initials: "RM" },
      { quote: ["AI reduced a lot of repetitive work. ", "We gained organization and speed", " without losing legal control."], name: "Juliana Costa", role: "Operations · GlobalVisa", initials: "JC" },
    ],
  },
  pricing: {
    kicker: "Who it's for", title: "Aplikei was built for firms that sell immigration processes.",
    plans: [
      { label: "Immigration lawyers", price: "Operation", period: "with more control", features: ["Firms specialized in visas", "Migration consultancies", "Integrated commercial and financial operation"], cta: "Get started now", highlighted: false },
      { label: "Scaling teams", price: "Team", period: "integrated", features: ["Sales, managers and lawyers", "Flows organized by role", "Less dependence on parallel controls"], cta: "Get started now", highlighted: true },
      { label: "Digital firms", price: "AI", period: "applied", features: ["Sell services online", "Own sales page", "AI support for repetitive tasks"], cta: "Talk to a specialist", highlighted: false },
    ],
  },
  faq: {
    kicker: "FAQ", title: "Common questions",
    lead: "Quick answers about getting started, using the platform and managing your operation.",
    items: [
      { q: "How do I get started with Aplikei?", a: "Create your account, set up your firm and activate the solutions you want to sell. Then you can start using checkout, processes and team workflows." },
      { q: "What services can I sell on the platform?", a: "You can sell visas, consultations, RFE, COS and other immigration services with their own price, description, documents and workflow." },
      { q: "Can I migrate existing clients and cases?", a: "Yes. The platform is designed to centralize your operation and continue existing cases without losing history." },
      { q: "Does Aplikei replace the lawyer?", a: "No. It organizes the operation and reduces manual work, but the legal analysis and final decisions stay with your team." },
    ],
  },
  cta: { title: "Ready to turn your immigration firm into a digital operation?", desc: "Sell your services with personalized checkout, track each client in an organized flow and gain more control over processes, team, payments, payouts and operational tasks with AI support.", btn: "Get started now" },
  footer: {
    tagline: "Solutions, checkout, processes, team, finance and artificial intelligence integrated in one platform.",
    platform: "Platform", company: "Company", contact: "Contact",
    links: { solve: "Problem", automation: "Solution", how: "How it works", pricing: "Plans", about: "Who we are", security: "Data security", support: "Talk to a specialist" },
    legal: "© 2026 Aplikei Technologies. Aplikei is a technology platform, not a law firm.",
    terms: "Terms", privacy: "Privacy",
  },
  mobileUI: {
    nav: "MY CASES",
    title: "F-1 VISA",
    subtitle: "STUDENT/ACADEMIC",
    office: "ALMEIDA & PARTNERS",
    step: "DS-160 FORM",
    cta: "START STEP 1",
    panel: "DASHBOARD",
    active: "ACTIVE",
    progress: "0%",
    nextStep1: "RECEIVE I-20",
    nextStep2: "SCHEDULE INTERVIEW",
  },
};

export default landing;
