alter table public.services
  add column if not exists description text;

update public.services set description = case slug
  when 'visa-b1b2'
    then 'Processo completo para obtenção do visto B1/B2, utilizado para viagens de negócios e turismo aos EUA.'
  when 'visa-f1'
    then 'Processo para o visto F-1, destinado a estudantes internacionais matriculados em instituições americanas.'
  when 'visa-cos'
    then 'Mudança de categoria de visto dentro dos EUA, sem necessidade de sair do país.'
  when 'visa-eos'
    then 'Extensão do prazo de permanência no visto atual, mantendo o status legal nos EUA.'
  when 'dependent-b1b2'
    then 'Inclusão de dependente (cônjuge ou filho) no processo do visto B1/B2.'
  when 'dependent-f1'
    then 'Inclusão de dependente (cônjuge ou filho) no processo do visto F-1.'
  when 'dependent-cos'
    then 'Inclusão de dependente (cônjuge ou filho) no processo de Mudança de Status.'
  when 'dependent-eos'
    then 'Inclusão de dependente (cônjuge ou filho) no processo de Extensão de Status.'
  when 'analysis-rfe-cos'
    then 'Análise profissional de pedido de evidências adicionais (RFE) emitido pelo USCIS para Mudança de Status.'
  when 'analysis-rfe-eos'
    then 'Análise profissional de pedido de evidências adicionais (RFE) emitido pelo USCIS para Extensão de Status.'
  when 'mentoring-bronze'
    then 'Sessão de mentoria individual nível Bronze com orientação personalizada sobre o processo de visto.'
  when 'mentoring-silver'
    then 'Programa de mentoria nível Prata com acompanhamento mais detalhado e suporte estendido.'
  when 'mentoring-gold'
    then 'Programa de mentoria premium nível Ouro com acompanhamento completo, prioridade de atendimento e revisão de documentos.'
  when 'consultancy-motion-eos'
    then 'Consultoria avançada para elaboração de Motion to Reopen ou Reconsider em casos de Extensão de Status negada.'
  when 'consultancy-motion-cos'
    then 'Consultoria avançada para elaboração de Motion to Reopen ou Reconsider em casos de Mudança de Status negada.'
  when 'consultancy-negative-b1b2'
    then 'Consultoria especializada para casos com negativa prévia de visto B1/B2, avaliando as causas e estratégias de reapresentação.'
  when 'consultancy-negative-f1'
    then 'Consultoria especializada para casos com negativa prévia de visto F-1, avaliando as causas e estratégias de reapresentação.'
  else description
end;
