import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";
import { PDFDocument, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

function respond(payload: Record<string, unknown>, status = 200) {
  return new Response(JSON.stringify(payload), {
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    status,
  });
}

// ──────────────────────────────────────────────
// PDF builder helpers
// ──────────────────────────────────────────────
// eslint-disable-next-line @typescript-eslint/no-explicit-any
interface PageCtx {
  doc: any;
  fontBold: any;
  fontReg: any;
  page: any;
  y: number;
  margin: number;
  width: number;
}

function newPage(ctx: Omit<PageCtx, 'page' | 'y'>): PageCtx {
  const page = ctx.doc.addPage([612, 792]); // Letter
  return { ...ctx, page, y: 760, margin: 50, width: 512 };
}

function ensureSpace(ctx: PageCtx, needed = 20): PageCtx {
  if (ctx.y - needed < 60) return newPage(ctx);
  return ctx;
}

function drawHeader(ctx: PageCtx, title: string): PageCtx {
  let c = ensureSpace(ctx, 30);
  c.page.drawText(title, {
    x: c.margin, y: c.y,
    font: c.fontBold, size: 11,
    color: rgb(0.1, 0.2, 0.6),
  });
  c.y -= 6;
  c.page.drawLine({
    start: { x: c.margin, y: c.y },
    end: { x: c.margin + c.width, y: c.y },
    thickness: 0.5, color: rgb(0.1, 0.2, 0.6),
  });
  c.y -= 14;
  return c;
}

function drawField(ctx: PageCtx, label: string, value: unknown): PageCtx {
  if (!value && value !== 0) return ctx;
  let c = ensureSpace(ctx, 16);
  const text = `${label}: ${String(value)}`;
  c.page.drawText(text, {
    x: c.margin, y: c.y,
    font: c.fontReg, size: 9,
    color: rgb(0.15, 0.15, 0.15),
    maxWidth: c.width,
  });
  c.y -= 14;
  return c;
}

function drawYesNo(ctx: PageCtx, label: string, value: unknown): PageCtx {
  if (!value) return ctx;
  const display = value === 'yes' ? 'YES' : value === 'no' ? 'NO' : String(value);
  return drawField(ctx, label, display);
}

function drawSpacer(ctx: PageCtx): PageCtx {
  let c = ensureSpace(ctx, 10);
  c.y -= 6;
  return c;
}

// ──────────────────────────────────────────────
// Main handler
// ──────────────────────────────────────────────
Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  let step = 'init';
  try {
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    step = 'auth';
    const token = (req.headers.get('Authorization') ?? '').replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabaseAdmin.auth.getUser(token);
    if (authError || !user) return respond({ error: 'Usuário não autenticado.' });

    const { formData: fd, userServiceId } = await req.json();
    console.log(`[fill-i539] ServiceID: ${userServiceId} UserID: ${user.id}`);

    // ── Build PDF ──────────────────────────────
    step = 'build_pdf';
    const doc = await PDFDocument.create();
    const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
    const fontReg  = await doc.embedFont(StandardFonts.Helvetica);

    // Cover / title page
    let ctx = newPage({ doc, fontBold, fontReg, margin: 50, width: 512 });
    ctx.page.drawText('Form I-539 — Application To Extend/Change Nonimmigrant Status', {
      x: ctx.margin, y: ctx.y,
      font: ctx.fontBold, size: 13,
      color: rgb(0.05, 0.15, 0.5),
    });
    ctx.y -= 18;
    ctx.page.drawText(`Generated by Aplikei Pass  •  ${new Date().toLocaleDateString('en-US')}`, {
      x: ctx.margin, y: ctx.y,
      font: ctx.fontReg, size: 9,
      color: rgb(0.5, 0.5, 0.5),
    });
    ctx.y -= 30;

    // Part 1 – Personal Info
    ctx = drawHeader(ctx, 'PART 1 — INFORMATION ABOUT YOU');
    ctx = drawField(ctx, 'Family Name',             fd.i539_family_name);
    ctx = drawField(ctx, 'Given Name',              fd.i539_given_name);
    ctx = drawField(ctx, 'Middle Name',             fd.i539_middle_name);
    ctx = drawField(ctx, 'A-Number',                fd.i539_alien_reg_number);
    ctx = drawField(ctx, 'USCIS Online Acct #',     fd.i539_uscis_online_account_number);
    ctx = drawField(ctx, 'SSN',                     fd.i539_ssn);
    ctx = drawSpacer(ctx);

    ctx = drawField(ctx, 'Mailing — In Care Of',    fd.i539_mailing_in_care_of);
    ctx = drawField(ctx, 'Mailing — Street',        fd.i539_mailing_street);
    ctx = drawField(ctx, 'Mailing — Apt/Ste/Flr',  fd.i539_mailing_apt_ste_flr);
    ctx = drawField(ctx, 'Mailing — City',          fd.i539_mailing_city);
    ctx = drawField(ctx, 'Mailing — State',         fd.i539_mailing_state);
    ctx = drawField(ctx, 'Mailing — ZIP',           fd.i539_mailing_zip);

    if (fd.i539_is_mailing_same_as_physical) {
      ctx = drawField(ctx, 'Physical Address',      'Same as mailing');
    } else {
      ctx = drawField(ctx, 'Physical — Street',     fd.i539_physical_street);
      ctx = drawField(ctx, 'Physical — City',       fd.i539_physical_city);
      ctx = drawField(ctx, 'Physical — State',      fd.i539_physical_state);
      ctx = drawField(ctx, 'Physical — ZIP',        fd.i539_physical_zip);
    }
    ctx = drawSpacer(ctx);

    ctx = drawField(ctx, 'Country of Birth',        fd.i539_country_of_birth);
    ctx = drawField(ctx, 'Country of Citizenship',  fd.i539_country_of_citizenship);
    ctx = drawField(ctx, 'Date of Birth',           fd.i539_date_of_birth);
    ctx = drawField(ctx, 'Date of Last Arrival',    fd.i539_last_arrival_date);
    ctx = drawField(ctx, 'I-94 Number',             fd.i539_i94_number);
    ctx = drawField(ctx, 'Passport Number',         fd.i539_passport_number);
    ctx = drawField(ctx, 'Travel Document Number',  fd.i539_travel_document_number);
    ctx = drawField(ctx, 'Country of Issuance',     fd.i539_country_passport_issuance);
    ctx = drawField(ctx, 'Passport Expiration',     fd.i539_passport_expiration_date);
    ctx = drawField(ctx, 'Current Status',          fd.i539_current_nonimmigrant_status);
    ctx = drawField(ctx, 'Status Expiration',       fd.i539_status_expiration_date);
    if (fd.i539_granted_duration_of_status) ctx = drawField(ctx, 'Duration of Status (D/S)', 'YES');
    ctx = drawSpacer(ctx);

    // Part 2 & 3 – Application
    ctx = drawHeader(ctx, 'PART 2 & 3 — APPLICATION & PROCESSING');
    ctx = drawField(ctx, 'Application Type',        fd.i539_application_type);
    ctx = drawField(ctx, 'Change Status To',        fd.i539_change_status_to);
    ctx = drawField(ctx, 'Effective Date',          fd.i539_effective_date_requested);
    ctx = drawField(ctx, 'Number of Applicants',    fd.i539_number_of_applicants);
    ctx = drawField(ctx, 'Total People',            fd.i539_total_people);
    ctx = drawField(ctx, 'School Name',             fd.i539_school_name);
    ctx = drawField(ctx, 'SEVIS ID',                fd.i539_sevis_id);
    ctx = drawField(ctx, 'Extend Until',            fd.i539_extended_until_date);
    ctx = drawField(ctx, 'USCIS Receipt Number',    fd.i539_uscis_receipt_number);
    if (fd.i539_is_based_on_prior_approval)   ctx = drawField(ctx, 'Based on Prior Approval', 'YES');
    if (fd.i539_is_based_on_pending_petition) ctx = drawField(ctx, 'Based on Pending Petition', 'YES');
    ctx = drawSpacer(ctx);

    // Part 4 – Security
    ctx = drawHeader(ctx, 'PART 4 — ADDITIONAL INFORMATION (SECURITY)');
    ctx = drawYesNo(ctx, 'Immigrant visa applicant?',              fd.i539_immigrant_visa_applicant);
    ctx = drawYesNo(ctx, 'Immigrant petition filed?',              fd.i539_immigrant_petition_filed);
    ctx = drawYesNo(ctx, 'Filed Form I-485?',                      fd.i539_filed_i485);
    ctx = drawYesNo(ctx, 'Criminal history?',                      fd.i539_criminal_history);
    ctx = drawYesNo(ctx, '7a. Acts involving torture/genocide?',   fd.i539_q7a);
    ctx = drawYesNo(ctx, '7b. Killing any person?',                fd.i539_q7b);
    ctx = drawYesNo(ctx, '8a. Military/paramilitary/rebel?',       fd.i539_q8a);
    ctx = drawYesNo(ctx, '8b. Prison/detention facility?',         fd.i539_q8b);
    ctx = drawYesNo(ctx, '10. Sold/provided weapons?',             fd.i539_q10);
    ctx = drawYesNo(ctx, '11. Received weapons training?',         fd.i539_q11);
    ctx = drawYesNo(ctx, '12. Violated nonimmigrant status?',      fd.i539_q12);
    ctx = drawYesNo(ctx, '13. In removal proceedings?',            fd.i539_q13);
    ctx = drawYesNo(ctx, '14. Employed in US since last entry?',   fd.i539_q14);
    ctx = drawSpacer(ctx);

    // Part 5 – Contact
    ctx = drawHeader(ctx, 'PART 5 — CONTACT INFORMATION');
    ctx = drawField(ctx, 'Daytime Phone',           fd.i539_applicant_phone);
    ctx = drawField(ctx, 'Mobile Phone',            fd.i539_applicant_mobile);
    ctx = drawField(ctx, 'Email',                   fd.i539_applicant_email);
    ctx = drawField(ctx, 'Interpreter',             fd.i539_interpreter_info);
    ctx = drawField(ctx, 'Preparer',                fd.i539_preparer_info);

    // Dependents
    const dependents: Array<{ name: string; birthDate: string; relationship: string }> =
      fd.dependents ?? [];
    if (dependents.length > 0) {
      ctx = drawSpacer(ctx);
      ctx = drawHeader(ctx, 'I-539A — DEPENDENTS');
      for (const dep of dependents) {
        ctx = drawField(ctx, 'Name',         dep.name);
        ctx = drawField(ctx, 'Birth Date',   dep.birthDate);
        ctx = drawField(ctx, 'Relationship', dep.relationship);
        ctx = drawSpacer(ctx);
      }
    }

    // ── Save ───────────────────────────────────
    step = 'save_pdf';
    const pdfBytes = await doc.save();

    // ── Upload ─────────────────────────────────
    step = 'upload';
    const fileName = `cos_i539_${userServiceId}_${Date.now()}.pdf`;
    const bucket = 'process-documents';
    const { error: uploadErr } = await supabaseAdmin.storage
      .from(bucket)
      .upload(fileName, pdfBytes, { contentType: 'application/pdf', upsert: true });
    if (uploadErr) return respond({ error: `Erro no upload: ${uploadErr.message}` });

    // ── DB record ──────────────────────────────
    step = 'db';
    const { error: dbErr } = await supabaseAdmin
      .from('documents')
      .upsert({
        user_id: user.id,
        user_service_id: userServiceId,
        name: 'cos_i539',
        storage_path: fileName,
        bucket_id: bucket,
        status: 'pending',
      }, { onConflict: 'user_id,name' });
    if (dbErr) return respond({ error: `Erro no banco: ${dbErr.message}` });

    console.log(`[fill-i539] OK: ${fileName}`);
    return respond({ success: true, fileName });

  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[fill-i539] erro em "${step}":`, msg);
    return respond({ error: `[${step}] ${msg}` });
  }
});
